### ISSUE TITLE
EX_STYLE_<COLOR>_BAR won't render correctly

### ISSUE THREAD

**Issue by twesemey** [useblocks/sphinx-needs#1401]
**Problem:**

From some version after 2.0.0 the `<color>_bar` style is broken.
Even the official documentation does not show this style correctly rendered.

https://sphinx-needs.readthedocs.io/en/latest/layout_styles.html#EX_STYLE_GREEN_BAR

![Image](https://github.com/user-attachments/assets/5fa3db22-e6b0-442d-987f-5fa2ed037815)

**Expected:**

Something similar to
![Image](https://github.com/user-attachments/assets/1d1023ec-380d-49bc-b78d-d1ebc71e7e92)

**Background:**

It seems that `--sn-bar-green` is not defined / set. Changing the value to a color worked. 
```css
table.needs_style_green_bar {
  background: linear-gradient(to right, transparent 90%, green 10%);
    background-color: rgba(0, 0, 0, 0);
}
```

**Solution:**

Some inspection revealed that the update variable names were not taken into account for the bar style. Actual variable name:
```css
   --sn-color-bar-green: #05c46b;
```
